config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  scope "/api" do
    scope "/v1" do
      get "/ad/:id", format: "json", to: "api/v1#ad_show", as: "apiv1_ad_show"
      get "/woeid/:id/:type", format: "json", to: "api/v1#woeid_show", as: "apiv1_woeid_show"
      get "/woeid/list", format: "json", to: "api/v1#woeid_list", as: "apiv1_woeid_list"
    end
  end

  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "callbacks" }

  constraints locale: /#{I18n.available_locales.join("|")}/ do
    get "/locales/:locale", to: "locales#show", as: :locale

    # i18n
    scope "(:locale)" do
      root "woeid#show", defaults: { type: "give" }

      # FIXME: type on ads#create instead of params
      resources :ads, path: "ad",
                      path_names: { new: "create" },
                      except: %i[index show] do
        resources :comments, only: :create
      end

      resources :users, only: [] do
        resources :reports, only: :create
      end

      scope "/ad" do
        get "/:id/:slug", to: "ads#show", as: "adslug"
        get "/edit/id/:id", to: "ads#edit", as: "ads_edit"
        post "/bump/id/:id", to: "ads#bump", as: "ads_bump"
        post "/change_status/id/:id",
             to: "ads#change_status",
             as: "ads_change_status"
        constraints(FullListConstraint.new) do
          get "/listall/ad_type/:type(/status/:status)(/page/:page)",
              to: "woeid#show",
              as: "ads_listall"
        end

        get "/listuser/id/:username(/type/:type)(/status/:status)(/page/:page)",
            to: redirect(ProfileUrlRewriter.new),
            constraints: { username: %r{[^/]+} }
      end

      # locations lists
      get "/woeid/:id/:type(/status/:status)(/page/:page)",
          to: "woeid#show",
          as: "ads_woeid",
          constraints: WoeidListConstraint.new

      # location change
      scope "/location" do
        get  "/change", to: "location#ask", as: "location_ask"
        get  "/change2", to: "location#change", as: "location_change"
        post "/change", to: "location#list"
        post "/change2", to: "location#change"
      end

      devise_for :users,
                 skip: %i[omniauth_callbacks unlocks],
                 controllers: { registrations: "registrations" },
                 path: "user",
                 path_names: {
                   sign_up: "register",
                   sign_in: "login",
                   sign_out: "logout",
                   password: "reset"
                 }

      # friendships
      resources :friendships, only: %i[create destroy]

      scope "/admin" do
        authenticate :user, ->(u) { u.admin? } do
          mount Sidekiq::Web, at: "/jobs"
        end
      end

      get "/profile/:username(/type/:type)(/status/:status)(/page/:page)",
          to: "users#profile",
          as: "profile",
          constraints: { username: %r{[^/]+} }

      # blocking
      resources :blockings, only: %i[create destroy]

      # messaging
      resources :conversations do
        member { delete "trash" }
        collection { delete "trash" }
      end

      # rss
      # nolotirov2 - legacy
      # FIX: las URLs legacy vienen asi
      # /en                     /rss/feed/woeid/766273                     /ad_type/give
      # Lo solucionamos en el nginx.conf y una configuracion para hacer el search and replace
      # http://stackoverflow.com/questions/22421522/nginx-rewrite-rule-for-replacing-space-whitespace-with-hyphen-and-convert-url-to
      scope "/rss" do
        get "/feed/woeid/:woeid/ad_type/:type", format: "rss", to: "rss#feed", as: "rss_type"
      end

      scope "/page" do
        get "/faqs", to: "page#faqs", as: "faqs"
        get "/rules", to: "page#rules", as: "rules"
        get "/about", to: "page#about", as: "about"
        get "/privacy", to: "page#privacy", as: "privacy"
        get "/legal", to: "page#legal", as: "legal"
        get "/translate", to: "page#translate", as: "translate"
      end

      # contact
      get "/contact", to: "contact#new", as: "contacts"
      post "/contact", to: "contact#create"

      # dismissing
      resources :announcements, only: [] do
        resources :dismissals, only: :create
      end
    end
  end
end

app/views/partials/_announcement.html.erb
<% if announcement %>
  <%= div_for announcement do %>
    <%= raw announcement.message %>

    <%= link_to '&times;'.html_safe,
                announcement_dismissals_path(announcement_id: announcement.id),
                method: :post,
                class: 'dismiss' %>
  <% end %>
<% end %>

app/views/partials/_flash.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class='flash-msg <%= name.to_s %>'>
      <%= msg.to_s %>
    </div>
  <% end %>
<% end %>

app/views/partials/_footer.html.erb
<div id="footer">
  <div class="upperWrap">

    <div class="links-right">
      <%= link_to t('nlt.about'), about_path %> |
      <%= link_to t('nlt.faqs'), faqs_path %> |
      <%= link_to t('nlt.rules'), rules_path %> |
      <%= link_to t('nlt.all_gifts'), ads_listall_path(type: 'give') %> |
      <%= link_to t('nlt.translations'), translate_path %> |
      &nbsp;&nbsp;

      <a href="https://alabs.org/">
        <%= image_tag("alabs.png", alt: "aLabs logo") %>
      </a>
    </div>
  </div>

  <div class="innerWrap">
    <p><%= t('nlt.footer_explain') %></p>
  </div>

  <div class="links-left">
    <%= link_to t('nlt.legal_notice'), legal_path %> |
    <%= link_to t('nlt.privacy'), privacy_path %> |
    <%= link_to t('nlt.developers'), 'https://github.com/alabs/nolotiro.org' %> |
    <%= link_to t('nlt.contact'), contact_path %> |
  </div>
</div>

app/views/partials/_google_adsense.html.erb
<div class="center">
  <%= render "partials/raw_google_adsense", class_name: class_name,
                                            ad_slot: ad_slot %>
</div>

app/views/partials/_header.html.erb
<div class="link-boxes">
  <%= render "partials/user_actions" %>
</div>

<div class="actions-row">
  <div class="site-logo">
    <%= link_to root_path, title: "nolotiro.org home" do %>
      <div class="site-name">nolotiro.org</div>
      <div class="site-slogan"><%= t('nlt.slogan') %></div>
    <% end %>
  </div>

  <% if content_for?(:action) %>
    <div class="page-actions">
      <%= yield(:action) %>
    </div>
  <% end %>
</div>

app/views/partials/_location_ranking.html.erb
<%= render layout: 'partials/ranking',
           locals: { title_key: title_key, ranking: ranking } do %>
  <% ranking.ranked.each do |id, name, n_ads| %>
    <li>
      <%= link_to "#{name} (#{n_ads})", ads_woeid_path(id, type: "give") %>
    </li>
  <% end %>
<% end %>

app/views/partials/_ranking.html.erb
<% if ranking.present? %>
  <div class="ranking">
    <h2><%= t("nlt.#{title_key}") %></h2>

    <ul>
      <%= yield %>
    </ul>
  </div>
<% end %>

app/views/partials/_rankings_sidebar.html.erb
<% unless current_woeid %>
  <%= render "partials/location_ranking", title_key: "cities_in_the_world",
                                          ranking: Ad.top_locations %>
<% end %>

<%= render "partials/user_ranking",
           title_key: "users_most_active_last_week",
           ranking: last_week_user_ranking %>

<%= render "partials/user_ranking",
           title_key: "users_most_active",
           ranking: overall_user_ranking %>

<div class="google_ad_wrapper">
  <%= render "partials/raw_google_adsense", class_name: "desktop google_adsense_600_160", ad_slot: "6783776462" %>
  <%= render "partials/google_adsense", class_name: "mobile google_adsense_300_250", ad_slot: "8702329269" %>
</div>

app/views/partials/_raw_google_adsense.html.erb
<ins class="adsbygoogle <%= class_name %>"
     style="display:inline-block;"
     data-ad-client="ca-pub-5360961269901609"
     data-ad-slot="<%= ad_slot %>"></ins>

app/views/partials/_select_language_box.html.erb
<button type='button' id='dLabel' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
  <i class='glyphicon glyphicon-globe'></i>
  <%= available_languages[I18n.locale] %>
  <span class='caret'></span>
</button>

<ul class='dropdown-menu' aria-labelledby='dLabel'>
  <% available_languages.each do |abbr, language| %>
    <li>
      <%= link_to locale_path(abbr), class: 'lang', 'data-langcode' => abbr do %>
        <span><%= language %></span>
      <% end %>
    </li>
  <% end %>

  <li>
    <%= link_to 'Otro...', translate_path, class: 'lang' %>
  </li>
</ul>

app/views/partials/_user_actions.html.erb
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <%= link_to admin_root_path, class: 'box-entry' do %>
      <span>
        <i class='glyphicon glyphicon-fire'></i>
      </span>
    <% end %>
  <% end %>

  <%= link_to profile_path(current_user.username), class:'box-entry' do %>
    <span>
      <b><%= current_user.username %></b>
    </span>
  <% end %>

  <%= link_to conversations_path, class: 'box-entry' do %>
    <span>
      <i class='glyphicon glyphicon-envelope'></i>
      <b><%= conversations_count %></b>
    </span>
  <% end %>

  <%= link_to destroy_user_session_path, method: :delete, class: 'box-entry' do %>
    <span><%= t('nlt.logout') %></span>
  <% end %>
<% else %>
  <%= link_to new_user_registration_path, class: 'box-entry' do %>
    <span><%= t('nlt.new_user') %></span>
  <% end %>

  <%= link_to new_user_session_path, class: 'box-entry' do %>
    <span><%= t('nlt.login') %></span>
  <% end %>
<% end %>

<span class='box-entry'>
  <%= render 'partials/select_language_box' %>
</span>

app/views/partials/_user_ranking.html.erb
<%= render layout: 'partials/ranking',
           locals: { title_key: title_key, ranking: ranking } do %>
  <% ranking.ranked.each do |id, name, n_ads| %>
    <li>
      <%= link_to "#{name} (#{n_ads})", profile_path(name) %>
    </li>
  <% end %>
<% end %>