config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  scope "/api" do
    scope "/v1" do
      get "/ad/:id", format: "json", to: "api/v1#ad_show", as: "apiv1_ad_show"
      get "/woeid/:id/:type", format: "json", to: "api/v1#woeid_show", as: "apiv1_woeid_show"
      get "/woeid/list", format: "json", to: "api/v1#woeid_list", as: "apiv1_woeid_list"
    end
  end

  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "callbacks" }

  constraints locale: /#{I18n.available_locales.join("|")}/ do
    get "/locales/:locale", to: "locales#show", as: :locale

    # i18n
    scope "(:locale)" do
      root "woeid#show", defaults: { type: "give" }

      # FIXME: type on ads#create instead of params
      resources :ads, path: "ad",
                      path_names: { new: "create" },
                      except: %i[index show] do
        resources :comments, only: :create
      end

      resources :users, only: [] do
        resources :reports, only: :create
      end

      scope "/ad" do
        get "/:id/:slug", to: "ads#show", as: "adslug"
        get "/edit/id/:id", to: "ads#edit", as: "ads_edit"
        post "/bump/id/:id", to: "ads#bump", as: "ads_bump"
        post "/change_status/id/:id",
             to: "ads#change_status",
             as: "ads_change_status"
        constraints(FullListConstraint.new) do
          get "/listall/ad_type/:type(/status/:status)(/page/:page)",
              to: "woeid#show",
              as: "ads_listall"
        end

        get "/listuser/id/:username(/type/:type)(/status/:status)(/page/:page)",
            to: redirect(ProfileUrlRewriter.new),
            constraints: { username: %r{[^/]+} }
      end

      # locations lists
      get "/woeid/:id/:type(/status/:status)(/page/:page)",
          to: "woeid#show",
          as: "ads_woeid",
          constraints: WoeidListConstraint.new

      # location change
      scope "/location" do
        get  "/change", to: "location#ask", as: "location_ask"
        get  "/change2", to: "location#change", as: "location_change"
        post "/change", to: "location#list"
        post "/change2", to: "location#change"
      end

      devise_for :users,
                 skip: %i[omniauth_callbacks unlocks],
                 controllers: { registrations: "registrations" },
                 path: "user",
                 path_names: {
                   sign_up: "register",
                   sign_in: "login",
                   sign_out: "logout",
                   password: "reset"
                 }

      # friendships
      resources :friendships, only: %i[create destroy]

      scope "/admin" do
        authenticate :user, ->(u) { u.admin? } do
          mount Sidekiq::Web, at: "/jobs"
        end
      end

      get "/profile/:username(/type/:type)(/status/:status)(/page/:page)",
          to: "users#profile",
          as: "profile",
          constraints: { username: %r{[^/]+} }

      # blocking
      resources :blockings, only: %i[create destroy]

      # messaging
      resources :conversations do
        member { delete "trash" }
        collection { delete "trash" }
      end

      # rss
      # nolotirov2 - legacy
      # FIX: las URLs legacy vienen asi
      # /en                     /rss/feed/woeid/766273                     /ad_type/give
      # Lo solucionamos en el nginx.conf y una configuracion para hacer el search and replace
      # http://stackoverflow.com/questions/22421522/nginx-rewrite-rule-for-replacing-space-whitespace-with-hyphen-and-convert-url-to
      scope "/rss" do
        get "/feed/woeid/:woeid/ad_type/:type", format: "rss", to: "rss#feed", as: "rss_type"
      end

      scope "/page" do
        get "/faqs", to: "page#faqs", as: "faqs"
        get "/rules", to: "page#rules", as: "rules"
        get "/about", to: "page#about", as: "about"
        get "/privacy", to: "page#privacy", as: "privacy"
        get "/legal", to: "page#legal", as: "legal"
        get "/translate", to: "page#translate", as: "translate"
      end

      # contact
      get "/contact", to: "contact#new", as: "contacts"
      post "/contact", to: "contact#create"

      # dismissing
      resources :announcements, only: [] do
        resources :dismissals, only: :create
      end
    end
  end
end

app/controllers/woeid_controller.rb
# frozen_string_literal: true

class WoeidController < ApplicationController
  include StringUtils

  before_action :check_location

  def show
    @type = type_scope || "give"
    @status = status_scope || "currently_available"
    @q = params[:q]
    @page = params[:page]

    scope = Ad.public_send(@type).by_woeid_code(current_woeid).by_title(@q)
    scope = scope.public_send(@status) if @type == "give"

    @ads = policy_scope(scope).includes(:user, town: [:state, :country])
                              .recent_first
                              .page(@page)
  end

  private

  def check_location
    redirect_to location_ask_path if user_signed_in? && user_woeid.nil?

    return unless current_woeid

    @town = Town.find(current_woeid)
  end
end

app/helpers/woeid_helper.rb
# frozen_string_literal: true

module WoeidHelper
  def self.convert_woeid_name(woeid)
    locale = I18n.locale
    key = "woeid_" + locale.to_s + "_" + woeid.to_s
    value = Rails.cache.fetch(key)
    return value if value

    query = <<-SQL.squish
      select * from geo.places where woeid = #{woeid} AND lang = '#{locale}'
    SQL

    place_raw = Yahoo::Fetcher.new(query).fetch
    return if place_raw.nil?

    place = Yahoo::Location.new(place_raw)
    return unless place.town?

    value = { full: place.fullname, short: place.name }
    Rails.cache.write(key, value)
    value
  end

  def self.search_by_name(name)
    return [] if name.blank?

    query = <<-SQL.squish
      select * from geo.places
      where text = '#{name}' AND placetype = '7' AND lang = '#{I18n.locale}'
    SQL

    raw_locations = Yahoo::Fetcher.new(query).fetch
    return [] if raw_locations.nil?

    Yahoo::ResultSet.new(Array.wrap(raw_locations))
  end
end

app/views/woeid/_filter_status.html.erb
<div class="filter_status">
  <%= link_to t('nlt.available'),
              ad_listing_path('give', 'available'),
              @status == "currently_available" ? { class: "actual" } : {} %>

  <%= link_to t('nlt.booked'),
              ad_listing_path('give', 'booked'),
              @status == "currently_booked" ? { class: "actual" } : {} %>

  <%= link_to t('nlt.delivered'),
              ad_listing_path('give', 'delivered'),
              @status == "currently_delivered" ? { class: "actual" } : {} %>
</div>

app/views/woeid/show.html.erb
<% content_for :title, listing_page_title %>

<% if current_woeid %>
  <% content_for :meta_description,
                 t('nlt.gift_on', woeid: @town.fullname) %>
<% end %>

<% if current_woeid && @status == 'available' %>
  <% content_for :meta_extra do %>
    <link rel="alternate"
          type="application/rss+xml"
          title="nolotiro.org - <%= @town.fullname %>"
          href="<%= rss_type_url(woeid: current_woeid, type: @type) %>" />
  <% end %>
<% end %>

<% content_for :action do %>
  <div class="ad_change_location_home">
    <% if current_woeid %>
      <%= link_to t('nlt.change_city'), location_ask_path %>
    <% elsif location_suggest %>
      <% title = t('nlt.view_ads_on', location: location_suggest.name) %>
      <%= link_to_change_location location_suggest.fullname, title %>
    <% else %>
      <%= link_to t('nlt.view_ads_on_your_city'), location_ask_path %>
    <% end %>
  </div>

  <div class="ad_create_tab">
    <% if current_woeid %>
      <%= link_to "+ #{t('nlt.publish_ad_on', woeid: @town.name)}",
                  new_ad_path %>
    <% else %>
      <%= link_to "+ #{t('nlt.publish_ad')}", new_ad_path %>
    <% end %>
  </div>
<% end %>

<div class="main-row">
  <div class="col-md-9 col-sm-9">
    <ul class="nav nlt-tabs">
      <li role="presentation" class="<%= 'active' if @type == "give" %>">
        <%= link_to t('nlt.gifts'), ad_listing_path('give') %>
      </li>

      <li role="presentation" class="<%= 'active' if @type == "want" %>">
        <%= link_to t('nlt.requests'), ad_listing_path('want') %>
      </li>
    </ul>

    <div class="location_header_section">
      <div class="location_name">
        <h1>
          <% if current_woeid.nil? %>
            <%= t("nlt.all_#{@type == 'want' ? 'requests' : 'gifts'}") %>
          <% else %>
            <%= t('nlt.searching_on_html', q: @q) if @q %>

            <%= @town.fullname %>
          <% end %>
        </h1>

        <br>
        <%= render "ads/search", q: @q %>

        <%= link_to location_ask_path do %>
          <i class="glyphicon glyphicon-map-marker"></i>
          <%= t('nlt.change_city') %>
        <% end %>
      </div>
    </div>

    <div class="unpadded_content_section">
      <% if @type == "give" %>
        <%= render "filter_status" %>
      <% end %>

      <% if @ads.any? %>
        <%= render 'ads/list_with_adsense', ads: @ads %>

        <%= paginate @ads, params: { id: current_woeid }, window: 1 %>
      <% elsif @q %>
        <%
          # @todo In the future we might want to enhance this page with interesting
          # content for the user, such as related searches or hits in locations a
          # little bit further away. But for now this is a dummy page where google
          # is giving soft 404 errors. So just remove indexing for now
        %>
        <% content_for :robots, 'noindex, nofollow' %>

        <%= render "ads/no_results_search" %>
      <% else %>
        <%= render "ads/no_results" %>
      <% end %>

      <% if current_woeid && @status == 'available' %>
        <div class="rss">
          <%= link_to rss_type_path(woeid: current_woeid, type: "give") do %>
            <%= image_tag "rss.png", alt: t("nlt.rss_suscribe") %>
            &nbsp; <%= t('nlt.rss_suscribe') %> - <%= @town.fullname %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="col-md-3 col-sm-3">
    <%= render 'partials/rankings_sidebar' %>
  </div>
</div>