config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  scope "/api" do
    scope "/v1" do
      get "/ad/:id", format: "json", to: "api/v1#ad_show", as: "apiv1_ad_show"
      get "/woeid/:id/:type", format: "json", to: "api/v1#woeid_show", as: "apiv1_woeid_show"
      get "/woeid/list", format: "json", to: "api/v1#woeid_list", as: "apiv1_woeid_list"
    end
  end

  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "callbacks" }

  constraints locale: /#{I18n.available_locales.join("|")}/ do
    get "/locales/:locale", to: "locales#show", as: :locale

    # i18n
    scope "(:locale)" do
      root "woeid#show", defaults: { type: "give" }

      # FIXME: type on ads#create instead of params
      resources :ads, path: "ad",
                      path_names: { new: "create" },
                      except: %i[index show] do
        resources :comments, only: :create
      end

      resources :users, only: [] do
        resources :reports, only: :create
      end

      scope "/ad" do
        get "/:id/:slug", to: "ads#show", as: "adslug"
        get "/edit/id/:id", to: "ads#edit", as: "ads_edit"
        post "/bump/id/:id", to: "ads#bump", as: "ads_bump"
        post "/change_status/id/:id",
             to: "ads#change_status",
             as: "ads_change_status"
        constraints(FullListConstraint.new) do
          get "/listall/ad_type/:type(/status/:status)(/page/:page)",
              to: "woeid#show",
              as: "ads_listall"
        end

        get "/listuser/id/:username(/type/:type)(/status/:status)(/page/:page)",
            to: redirect(ProfileUrlRewriter.new),
            constraints: { username: %r{[^/]+} }
      end

      # locations lists
      get "/woeid/:id/:type(/status/:status)(/page/:page)",
          to: "woeid#show",
          as: "ads_woeid",
          constraints: WoeidListConstraint.new

      # location change
      scope "/location" do
        get  "/change", to: "location#ask", as: "location_ask"
        get  "/change2", to: "location#change", as: "location_change"
        post "/change", to: "location#list"
        post "/change2", to: "location#change"
      end

      devise_for :users,
                 skip: %i[omniauth_callbacks unlocks],
                 controllers: { registrations: "registrations" },
                 path: "user",
                 path_names: {
                   sign_up: "register",
                   sign_in: "login",
                   sign_out: "logout",
                   password: "reset"
                 }

      # friendships
      resources :friendships, only: %i[create destroy]

      scope "/admin" do
        authenticate :user, ->(u) { u.admin? } do
          mount Sidekiq::Web, at: "/jobs"
        end
      end

      get "/profile/:username(/type/:type)(/status/:status)(/page/:page)",
          to: "users#profile",
          as: "profile",
          constraints: { username: %r{[^/]+} }

      # blocking
      resources :blockings, only: %i[create destroy]

      # messaging
      resources :conversations do
        member { delete "trash" }
        collection { delete "trash" }
      end

      # rss
      # nolotirov2 - legacy
      # FIX: las URLs legacy vienen asi
      # /en                     /rss/feed/woeid/766273                     /ad_type/give
      # Lo solucionamos en el nginx.conf y una configuracion para hacer el search and replace
      # http://stackoverflow.com/questions/22421522/nginx-rewrite-rule-for-replacing-space-whitespace-with-hyphen-and-convert-url-to
      scope "/rss" do
        get "/feed/woeid/:woeid/ad_type/:type", format: "rss", to: "rss#feed", as: "rss_type"
      end

      scope "/page" do
        get "/faqs", to: "page#faqs", as: "faqs"
        get "/rules", to: "page#rules", as: "rules"
        get "/about", to: "page#about", as: "about"
        get "/privacy", to: "page#privacy", as: "privacy"
        get "/legal", to: "page#legal", as: "legal"
        get "/translate", to: "page#translate", as: "translate"
      end

      # contact
      get "/contact", to: "contact#new", as: "contacts"
      post "/contact", to: "contact#create"

      # dismissing
      resources :announcements, only: [] do
        resources :dismissals, only: :create
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include MultiLingualizable
  include Pundit

  # TODO: comment captcha for ad creation/edition

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError do |_exception|
    redirect_to request.referer || root_path, alert: t("nlt.permission_denied")
  end

  def access_denied(exception)
    redirect_to root_url, alert: exception.message
  end

  def signed_in_root_path(resource)
    woeid = resource.woeid
    return ads_woeid_path(woeid, type: "give") if woeid

    location_ask_path
  end

  def authenticate_active_admin_user!
    authenticate_user!
    return if current_user.admin?

    flash[:alert] = t("nlt.permission_denied")
    redirect_to root_path
  end

  def type_scope
    %w[give want].include?(params[:type]) ? params[:type] : nil
  end

  def status_scope
    return unless %w[available booked delivered expired].include?(params[:status])

    "currently_#{params[:status]}"
  end

  def location_suggest
    @location_suggest ||= RequestGeolocator.new(request.remote_ip).suggest
  end

  helper_method :location_suggest

  def comment_counts
    @comment_counts ||=
      policy_scope(Comment.where(ads_id: @ads.ids)).group(:ads_id).size
  end

  helper_method :comment_counts

  def conversations_count
    @conversations_count ||=
      policy_scope(Conversation.unread_by(current_user)).size
  end

  helper_method :conversations_count

  def current_woeid
    @current_woeid ||=
      if request.path =~ %r{/listall/} || params[:controller] == "users"
        nil
      else
        params[:id].presence || user_woeid
      end
  end

  helper_method :current_woeid

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: %i[username email password password_confirmation remember_me])

    devise_parameter_sanitizer.permit(:sign_in,
                                      keys: %i[username email password remember_me])

    devise_parameter_sanitizer.permit(:account_update,
                                      keys: [:username])
  end

  private

  def user_woeid
    current_user.try(:woeid)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def messages_tab?
    params[:controller] == "conversations"
  end

  def profile_tab?
    (params[:controller] == "users" && params["action"] == "profile") ||
      (params[:controller] == "registrations" && params["action"] == "edit")
  end

  def ad_tab?
    params[:controller] == "users" && params["action"] == "profile"
  end

  def no_advertising_allowed?
    devise_controller?
  end

  def recaptcha
    recaptcha_tags(theme: "light", ajax: true, hl: I18n.locale)
  end

  def errors_for(object)
    errs = object.errors
    return unless errs.any?

    content_tag(:div, id: "error_explanation") do
      header = content_tag(:h2, t("nlt.save_failed"))
      list = content_tag(:ul) do
        safe_join(errs.full_messages.map { |m| content_tag(:li, m) }, "\n")
      end

      header + list
    end
  end

  def link_to_change_location(place, name = nil)
    title = name || place

    link_to title, location_change_path(location: place)
  end

  def available_languages
    {
      en: "English",
      es: "Español",
      ca: "Català",
      gl: "Galego",
      fr: "Français",
      pt: "Português",
      it: "Italiano"
    }
  end
end

app/views/application/_actions.html.erb
<ul class="profile-actions">
  <% if current_user.nil? || (blocking.nil? && current_user != user) %>
    <li class="list-group-item">
      <%= link_to new_conversation_path(recipient_id: user.id) do %>
        <i class="glyphicon glyphicon-envelope"></i>
        <%= t('nlt.profile_actions.contact') %>
      <% end %>
    </li>
  <% end %>

  <% if user_signed_in? %>
    <% if current_user == user %>
      <li class="list-group-item">
        <%= link_to profile_path(user.username) do %>
          <i class="glyphicon glyphicon-user"></i>
          <%= t('nlt.profile') %>
        <% end %>
      </li>

      <li class="list-group-item">
        <%= link_to edit_user_registration_path do %>
          <i class="glyphicon glyphicon-edit"></i>
          <%= t('nlt.profile_actions.edit') %>
        <% end %>
      </li>

      <li class="list-group-item">
        <%= link_to conversations_path do %>
          <i class="glyphicon glyphicon-envelope"></i>
          <%= t('nlt.messages') %>
        <% end %>
      </li>
    <% else %>
      <% if blocking %>
        <li class="list-group-item">
          <%= link_to blocking, method: :delete do %>
            <i class="glyphicon glyphicon-ok-circle"></i>
            <%= t('nlt.profile_actions.blocking.delete') %>
          <% end %>
        </li>
      <% else %>
        <li class="list-group-item">
          <% friendship = current_user.friend?(user) %>

          <% if friendship %>
            <%= link_to friendship, method: :delete do %>
              <i class="glyphicon glyphicon-remove"></i>
              <%= t('nlt.profile_actions.friend.delete', username: user.username) %>
            <% end %>
          <% else %>
            <%= link_to friendships_path(friend_id: user.id), method: :post do %>
              <i class="glyphicon glyphicon-ok"></i>
              <%= t('nlt.profile_actions.friend.add', username: user.username) %>
            <% end %>
          <% end %>
        </li>

        <li class="list-group-item">
          <%= link_to blockings_path(blocked_id: user.id),
                      data: { confirm: t('nlt.profile_actions.blocking.confirm', username: user.username) },
                      method: :post do %>
            <i class="glyphicon glyphicon-ban-circle"></i>
            <%= t('nlt.profile_actions.blocking.add') %>
          <% end %>
        </li>
      <% end %>

      <li class="list-group-item">
        <%= render 'report', user: user,
                             title: t('nlt.profile_actions.reporting.report') %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/application/_friends.html.erb
<% unless user.friends.count == 0 %>
  <div class="ranking">
    <h2><%= t('nlt.friends') %></h2>

    <ul>
      <% user.friends.each do |friend| %>
        <li>
          <%= link_to friend.username, profile_path(friend.username) %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/application/_profile.html.erb
<div class="main-row">
  <div class="col-md-9 col-sm-9">
    <div class="default_header_section">
      <%= render 'profile_header', user: user %>
    </div>

    <div class="unpadded_content_section">
      <%= yield %>
    </div>
  </div>

  <div class="col-md-3 col-sm-3">
    <%= render 'friends', user: user %>

    <div class="google_ad_wrapper">
      <%= render "partials/raw_google_adsense", class_name: "desktop google_adsense_600_160", ad_slot: "6783776462" %>
      <%= render "partials/google_adsense", class_name: "mobile google_adsense_300_250", ad_slot: "8702329269" %>
    </div>
  </div>
</div>

app/views/application/_profile_header.html.erb
<%= render 'actions',
           user: user,
           blocking: current_user ? current_user.blocking?(user) : nil %>

<h1><%= content_for :title %></h1>

<h4>
  <%= t('nlt.username') %>: <%= user.username %>
</h4>

<h4>
  <%= t('nlt.member_since') %>: <%= l user.created_at, format: :long %>
</h4>

app/views/application/_report.html.erb
<% if current_user.reported?(user) %>
  <i class="glyphicon glyphicon-ok"></i>
  <%= t('nlt.reported_user') %>
<% else %>
  <%= link_to user_reports_path(user),
              method: :post,
              data: { confirm: t('nlt.profile_actions.reporting.confirm', username: user.username) } do %>
    <i class="glyphicon glyphicon-flag"></i>
    <%= title %>
  <% end %>
<% end %>